=== Distrotech/texinfo/texinfo/makeinfo/texinfo.dtd
<!-- $Id: texinfo.dtd,v 1.7 2003-11-11 04:12:17 dirt Exp $
   Document Type Definition for Texinfo.

   Author: Philippe Martin (feloy@free.fr)
   Contributors:
           Karl Eichwalder (keichwa@gmx.net)
	   Alper Ersoy (dirt@gtk.org)

   Copyright (C) 2001, 2002, 2003 Free Software Foundation, Inc.

  Copying and distribution of this file, with or without modification,
  are permitted in any medium without royalty provided the copyright
  notice and this notice are preserved.

-->

<!-- ENTITIES -->

<!-- Meta-information -->
<!ENTITY % metainformation "setfilename | settitle | dircategory">
<!ENTITY % variables "setvalue | clearvalue">

<!-- Document language -->
<!ENTITY % lang "documentlanguage">

<!-- Language codes -->
<!ENTITY % languagecodes "aa|ab|af|am|ar|as|ay|az|ba|be|bg|bh|bi|bn|bo|br|ca|co|cs|cy|da|de|dz|el|en|eo|es|et|eu|fa|fi|fj|fo|fr|fy|ga|gd|gl|gn|gu|ha|he|hi|hr|hu|hy|ia|id|ie|ik|is|it|iu|ja|jw|ka|kk|kl|km|kn|ko|ks|ku|ky|la|ln|lo|lt|lv|mg|mi|mk|ml|mn|mo|mr|ms|mt|my|na|ne|nl|no|oc|om|or|pa|pl|ps|pt|qu|rm|rn|ro|ru|rw|sa|sd|sg|sh|si|sk|sl|sm|sn|so|sq|sr|ss|st|su|sv|sw|ta|te|tg|th|ti|tk|tl|tn|to|tr|ts|tt|tw|ug|uk|ur|uz|vi|vo|wo|xh|yi|yo|za|zh|zu">

<!-- ToC -->
<!ENTITY % toc "contents | shortcontents">

<!-- Title page -->
<!ENTITY % titlepage_cmds "author | booktitle | booksubtitle">

<!-- block -->
<!-- ***** -->
<!ENTITY % block "menu | para | quotation | example | smallexample | lisp
                  | smalllisp | cartouche | copying
                  | format | smallformat | display
                  | smalldisplay | itemize | enumerate | sp | center | group
                  | table | multitable | definition">

<!-- API definitions -->
<!-- *************** -->
<!ENTITY % definition.cmds "defcategory | deffunction | defvariable | defparam
			    | defdelimiter | deftype | defparamtype | defdatatype
			    | defclass | defclassvar | defoperation">

<!-- Headings -->
<!-- ******** -->
<!ENTITY % headings "majorheading | chapheading | heading | subheading
		     | subsubheading">


<!-- Sectioning -->
<!-- ********** -->
<!ENTITY % section.level1 "top | chapter | unnumbered | appendix">

<!ENTITY % section.level2 "section | unnumberedsec | appendixsec">

<!ENTITY % section.level3 "subsection | unnumberedsubsec | appendixsubsec">

<!ENTITY % section.level4 "subsubsection | unnumberedsubsubsec 
                           | appendixsubsubsec">

<!ENTITY % section.all "%section.level1; | %section.level2; | %section.level3;
                        | %section.level4;">


<!ENTITY % section.level1.content "(%block; 
                                   | %section.level2; 
                                   | %section.level3; 
                                   | %section.level4; 
				   | verbatim | titlepage | %toc;
				   | %lang; | %variables;
				   | %headings;
                                   | printindex)*">

<!ENTITY % section.level2.content "(%block; 
                                   | %section.level3; 
                                   | %section.level4;
				   | verbatim | titlepage | %toc;
				   | %lang; | %variables;
				   | %headings;)*">

<!ENTITY % section.level3.content "(%block; 
                                   | %section.level4;
				   | verbatim | titlepage | %toc;
				   | %lang; | %variables;
				   | %headings;)*">

<!ENTITY % section.level4.content "(%block;
				    | verbatim | titlepage | %toc;
				    | %lang; | %variables;
				    | %headings;)*">


<!-- Inline -->
<!-- ****** -->
<!ENTITY % Inline.emphasize "strong | emph">
<!ENTITY % Inline.smallcaps "sc">
<!ENTITY % Inline.fonts "i | b | tt | r | titlefont">
<!ENTITY % Inline.markup "code | command | env | file | option | samp | dfn | cite | key | kbd | var | acronym | url">
<!ENTITY % Inline.reference "xref | inforef | indexterm | email | uref">

<!ENTITY % Inline.phrase
           "%Inline.emphasize; | %Inline.smallcaps; | %Inline.fonts;
            | %Inline.markup; | %Inline.reference; ">


<!-- ************ -->
<!-- * ELEMENTS * -->
<!-- ************ -->

<!-- TOP Level Element -->
<!-- ***************** -->
<!ELEMENT texinfo ((%metainformation; | titlepage | node | %block; | %toc;
		    | %variables; | %lang;)* )>
<!ATTLIST texinfo xml:lang (%languagecodes;) 'en'>

<!-- meta-information -->
<!ELEMENT setfilename (#PCDATA)>
<!ELEMENT settitle    (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT dircategory (#PCDATA)>

<!ELEMENT setvalue    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT clearvalue  EMPTY>
<!ATTLIST setvalue
		name CDATA #REQUIRED>
<!ATTLIST clearvalue
		name CDATA #REQUIRED>

<!-- ToC -->
<!ELEMENT contents      EMPTY>
<!ELEMENT shortcontents EMPTY>

<!-- Document language -->
<!ELEMENT documentlanguage EMPTY>
<!ATTLIST documentlanguage xml:lang (%languagecodes;) 'en'>

<!-- Titlepage -->
<!ELEMENT titlepage    (%titlepage_cmds; | %block;)*>
<!ELEMENT author       (#PCDATA | %Inline.phrase;)*>
<!ELEMENT booktitle    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT booksubtitle (#PCDATA | %Inline.phrase;)*>

<!-- NODES -->
<!-- ***** -->
<!ELEMENT node (nodename, nodenext?, nodeprev?, nodeup?, 
                (%section.all; | %block; | %toc; | %lang;)*) >

<!ELEMENT nodename (#PCDATA)>
<!ELEMENT nodenext (#PCDATA)>
<!ELEMENT nodeprev (#PCDATA)>
<!ELEMENT nodeup   (#PCDATA)>

<!-- SECTIONING -->
<!-- ********** -->

<!ELEMENT top           (title?, (%section.level1.content;))>

<!ELEMENT chapter       (title?, (%section.level1.content;))>
<!ELEMENT section       (title?, (%section.level2.content;))>
<!ELEMENT subsection    (title?, (%section.level3.content;))>
<!ELEMENT subsubsection (title?, (%section.level4.content;))>

<!ELEMENT unnumbered          (title?, (%section.level1.content;))>
<!ELEMENT unnumberedsec       (title?, (%section.level2.content;))>
<!ELEMENT unnumberedsubsec    (title?, (%section.level3.content;))>
<!ELEMENT unnumberedsubsubsec (title?, (%section.level4.content;))>

<!ELEMENT appendix          (title?, (%section.level1.content;))>
<!ELEMENT appendixsec       (title?, (%section.level2.content;))>
<!ELEMENT appendixsubsec    (title?, (%section.level3.content;))>
<!ELEMENT appendixsubsubsec (title?, (%section.level4.content;))>

<!-- Headings and titles -->
<!ELEMENT majorheading  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT chapheading   (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT heading       (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT subheading    (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT subsubheading (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT title		(#PCDATA | %Inline.phrase; | footnote)*>

<!-- BLOCK Elements -->
<!-- ************** -->

<!ELEMENT quotation    (%block; | %Inline.phrase;)*>
<!ELEMENT example      (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smallexample (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT lisp         (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smalllisp    (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT cartouche    (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT copying      (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT format       (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smallformat  (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT display      (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smalldisplay (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT center       (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT group        (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT image        (#PCDATA)>

<!-- Whitespace in these elements are always preserved -->
<!ATTLIST example      xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smallexample xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST lisp         xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smalllisp    xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST display      xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smalldisplay xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST format       xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smallformat  xml:space (preserve) #FIXED 'preserve'>

<!ELEMENT verbatim     (#PCDATA)>
<!ATTLIST verbatim     xml:space (preserve) #FIXED 'preserve'>

<!ELEMENT para         (#PCDATA | %Inline.phrase; | footnote | %lang;)*>
<!ATTLIST para
	  role CDATA #IMPLIED>

<!ELEMENT menu ((menuentry | para)*)>
<!ELEMENT menuentry (menunode?, menutitle?, menucomment?)>
<!ELEMENT menunode (#PCDATA)>
<!ELEMENT menutitle (#PCDATA)>
<!ELEMENT menucomment (#PCDATA | para)*>

<!-- Lists -->
<!ELEMENT itemize (itemfunction, (item | itemize | enumerate | indexterm)*)>
<!ELEMENT enumerate (enumarg?, (item | itemize | enumerate)*)>
<!ATTLIST enumerate 
          first CDATA #IMPLIED>

<!ELEMENT item (%block;)*>
<!ELEMENT enumarg (#PCDATA)>

<!ELEMENT itemfunction (#PCDATA | %Inline.phrase;)*>

<!-- Tables -->
<!ELEMENT table (tableitem | indexterm)+>
<!ELEMENT tableitem (tableterm+, item)>
<!ELEMENT tableterm (#PCDATA | %Inline.phrase;)*>

<!ELEMENT multitable (columnfraction*, row*)>
<!ELEMENT columnfraction (#PCDATA)>
<!ELEMENT row (entry*)>
<!ELEMENT entry (#PCDATA | %Inline.phrase;)*>

<!-- API definitions -->
<!ELEMENT definition (definitionterm | definitionitem)+>
<!ELEMENT definitionterm (%definition.cmds; | indexterm)+>
<!ELEMENT definitionitem (%block;)*>

<!ELEMENT defcategory  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT deffunction  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defvariable  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defparam     (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defdelimiter (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT deftype      (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defparamtype (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defdatatype  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defclass     (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defclassvar  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defoperation (#PCDATA | %Inline.phrase; | footnote)*>

<!-- INLINE Elements -->
<!-- *************** -->

<!-- Emphasize -->
<!ELEMENT strong (#PCDATA | %Inline.phrase;)*>
<!ELEMENT emph   (#PCDATA | %Inline.phrase;)*>

<!-- small caps -->
<!ELEMENT sc (#PCDATA | %Inline.phrase;)*>

<!-- fonts -->
<!ELEMENT i  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT b  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT tt (#PCDATA | %Inline.phrase;)*>
<!ELEMENT r  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT notfixedwidth (#PCDATA | %Inline.phrase;)*>
<!ELEMENT titlefont   (#PCDATA | %Inline.phrase;)*>

<!-- markup -->
<!ELEMENT code    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT command (#PCDATA | %Inline.phrase;)*>
<!ELEMENT env     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT file    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT option  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT samp    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT dfn     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT cite    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT key     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT kbd     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT var     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT acronym (#PCDATA | %Inline.phrase;)*>
<!ELEMENT url     (#PCDATA | %Inline.phrase;)*>

<!-- reference -->
<!ELEMENT anchor EMPTY>
<!ATTLIST anchor
          name CDATA #IMPLIED>

<!ELEMENT xref (xrefnodename | xrefinfoname | xrefinfofile
                | xrefprintedname | xrefprinteddesc)*>
<!ELEMENT xrefnodename    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefinfoname    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefinfofile    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefprintedname (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefprinteddesc (#PCDATA | %Inline.phrase;)*>

<!ELEMENT inforef (inforefnodename | inforefrefname | inforefinfoname)*>
<!ELEMENT inforefnodename (#PCDATA | %Inline.phrase;)*>
<!ELEMENT inforefrefname  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT inforefinfoname (#PCDATA | %Inline.phrase;)*>

<!ELEMENT indexterm (#PCDATA | %Inline.phrase;)*>
<!ATTLIST indexterm
          index CDATA #IMPLIED>

<!ELEMENT email (emailaddress, emailname?)>
<!ELEMENT emailaddress (#PCDATA | %Inline.phrase;)*>
<!ELEMENT emailname (#PCDATA | %Inline.phrase;)*>

<!ELEMENT uref (urefurl, urefdesc?, urefreplacement?)>
<!ELEMENT urefurl         (#PCDATA | %Inline.phrase;)*>
<!ELEMENT urefdesc        (#PCDATA | %Inline.phrase;)*>
<!ELEMENT urefreplacement (#PCDATA | %Inline.phrase;)*>

<!ELEMENT footnote (para)>



<!ENTITY tex        "TeX">
<!ENTITY ellipsis   "">
<!ENTITY lt         "">
<!ENTITY gt         "">
<!ENTITY bullet     "">
<!ENTITY copyright  "">
<!ENTITY registered "">
<!ENTITY minus      "">
<!ENTITY linebreak  "">
<!ENTITY space      "">
<!ENTITY dots       "">
<!ENTITY enddots    "">
<!ENTITY amp        "">
<!ENTITY ldquo      "">
<!ENTITY rdquo      "">
<!ENTITY mdash      "">
<!ENTITY ndash      "">

<!ENTITY auml "">
<!ENTITY ouml "">
<!ENTITY uuml "">
<!ENTITY Auml "">
<!ENTITY Ouml "">
<!ENTITY Uuml "">
<!ENTITY Euml "">
<!ENTITY euml "">
<!ENTITY Iuml "">
<!ENTITY iuml "">
<!ENTITY yuml "">
<!ENTITY uml  "">

<!ENTITY Aacute "">
<!ENTITY Eacute "">
<!ENTITY Iacute "">
<!ENTITY Oacute "">
<!ENTITY Uacute "">
<!ENTITY Yacute "">
<!ENTITY aacute "">
<!ENTITY eacute "">
<!ENTITY iacute "">
<!ENTITY oacute "">
<!ENTITY uacute "">
<!ENTITY yacute "">

<!ENTITY ccedil "">
<!ENTITY Ccedil "">

<!ENTITY Acirc "">
<!ENTITY Ecirc "">
<!ENTITY Icirc "">
<!ENTITY Ocirc "">
<!ENTITY Ucirc "">
<!ENTITY acirc "">
<!ENTITY ecirc "">
<!ENTITY icirc "">
<!ENTITY ocirc "">
<!ENTITY ucirc "">

<!ENTITY Agrave "">
<!ENTITY Egrave "">
<!ENTITY Igrave "">
<!ENTITY Ograve "">
<!ENTITY Ugrave "">
<!ENTITY agrave "">
<!ENTITY egrave "">
<!ENTITY igrave "">
<!ENTITY ograve "">
<!ENTITY ugrave "">

<!ENTITY Atilde "">
<!ENTITY Ntilde "">
<!ENTITY Otilde "">
<!ENTITY atilde "">
<!ENTITY ntilde "">
<!ENTITY otilde "">

<!ENTITY oslash "">
<!ENTITY Oslash "">

<!ENTITY iexcl "">
<!ENTITY pound "">
<!ENTITY iquest "">
<!ENTITY AElig "">
<!ENTITY aelig "">
<!ENTITY OElig "">
<!ENTITY oelig "">
<!ENTITY Aring "">
<!ENTITY aring "">
<!ENTITY szlig "">

<!ENTITY macr "">


<!-- fixxme: not yet classified -->

<!ELEMENT sp (#PCDATA)>
<!ATTLIST sp
          lines CDATA #IMPLIED>
<!ELEMENT printindex (#PCDATA)>

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/two_footnotes_in_nodes_plain/two_footnotes_in_nodes.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>two_footnotes_in_nodes.xml</setfilename>

<node>
<nodename>Top</nodename>
<nodenext>chapter</nodenext>
<nodeup>(dir)</nodeup>
</node>
<unnumbered>
<title>2 footnotes in 2 nodes</title>

<para>A<footnote><para>Footnote Top/1
</para>
<para>para2
</para></footnote>
</para>
<para>B<footnote><para>Footnote Top/2
</para>
<para>para2
</para></footnote>
</para>
<menu>
<menuentry>
<menunode>chapter</menunode>
<menutitle>chapter</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</unnumbered>
<node>
<nodename>chapter</nodename>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>chapter</title>

<para>C<footnote><para>Footnote chapter/1
</para>
<para>para2
</para></footnote>
</para>
<para>D<footnote><para>Footnote chapter/2
</para>
<para>para2
</para></footnote>
</para>
</chapter>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/lower_subsub/lower_subsub.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">
<setfilename>lower_subsub.xml</setfilename>
<node>
<nodename>Top</nodename>
<nodenext>Chapter</nodenext>
<nodeup>(dir)</nodeup>
</node>
<unnumbered>
<title></title>

<menu>
<menuentry>
<menunode>Chapter</menunode>
<menutitle>Chapter</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</unnumbered>
<node>
<nodename>Chapter</nodename>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>Chapter</title>

<menu>
<menuentry>
<menunode>Section</menunode>
<menutitle>Section</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<node>
<nodename>Section</nodename>
<nodeup>Chapter</nodeup>
</node>
<section>
<title>Section</title>

<menu>
<menuentry>
<menunode>Subsection</menunode>
<menutitle>Subsection</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<node>
<nodename>Subsection</nodename>
<nodeup>Section</nodeup>
</node>
<subsection>
<title>Subsection</title>

<menu>
<menuentry>
<menunode>Subsubsection</menunode>
<menutitle>Subsubsection</menutitle>
<menucomment>
</menucomment>
</menuentry><menuentry>
<menunode>Lowered subsec</menunode>
<menutitle>Lowered subsec</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<node>
<nodename>Subsubsection</nodename>
<nodenext>Lowered subsec</nodenext>
<nodeup>Subsection</nodeup>
</node>
<subsubsection>
<title>Subsubsection</title>

<lowersections></lowersections></subsubsection>
<node>
<nodename>Lowered subsec</nodename>
<nodenext>Lowered subsubsection</nodenext>
<nodeprev>Subsubsection</nodeprev>
<nodeup>Subsection</nodeup>
</node>
<subsubsection>
<title>Lowered subsec</title>

<menu>
<menuentry>
<menunode>Lowered subsubsection</menunode>
<menutitle>Lowered subsubsection</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</subsubsection>
<node>
<nodename>Lowered subsubsection</nodename>
<nodeprev>Lowered subsec</nodeprev>
<nodeup>Subsection</nodeup>
</node>
<subsubsection>
<title>Lowered subsubsection</title>
<raisesections></raisesections>
<contents></contents>
</subsubsection>
</subsection>
</section>
</chapter>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/nodename_parentheses/nodename_parentheses.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">
<setfilename>nodename_parentheses.xml</setfilename>
<node>
<nodename>Top</nodename>
<nodenext>Node (with parentheses)</nodenext>
<nodeup>(dir)</nodeup>
</node>
<top>
<title>The top node</title>

<menu>
<menuentry>
<menunode>Node (with parentheses)</menunode>
<menutitle>Node (with parentheses)</menutitle>
<menucomment>
</menucomment>
</menuentry><menuentry>
<menunode>Other node</menunode>
<menutitle>Other node</menutitle>
<menucomment>
</menucomment>
</menuentry><menuentry>
<menunode>(manual)node</menunode>
<menutitle>(manual)node</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</top>
<node>
<nodename>Node (with parentheses)</nodename>
<nodenext>Other node</nodenext>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>Section (nodename with parentheses)</title>

<para>Dummy section
</para>
</chapter>
<node>
<nodename>Other node</nodename>
<nodeprev>Node (with parentheses)</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>Section (nodename without parentheses)</title>

<para>Dummy link to <xref><xrefnodename>Node (with parentheses)</xrefnodename></xref>.
</para>
<para>Dummy link to <xref><xrefnodename>(manual)node</xrefnodename></xref>.
</para>
</chapter>
<chapter>
<title>(manual)node</title>

<para>Dummy section with (manual)node node syntax.
</para>
<contents></contents>
</chapter>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/top/top.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>top.xml</setfilename>
<settitle>top test</settitle>

<!-- This traditional top node uses @ifinfo for testing. -->
<!-- Therefore there will be warnings when processing with -html. -->
<!-- The solution is to use @ifnottex instead. -->


<menu>
<menuentry>
<menunode> Subnode</menunode>
<menutitle> Subnode</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<node>
<nodename>Subnode</nodename>
<chapter>
<title>Subnode</title>

<para>Subnode.
</para>
</chapter>
</node>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/nodes_after_top/nodes_after_top.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>nodes_after_top.xml</setfilename>


<node>
<nodename>Top</nodename>
<nodenext>second node</nodenext>
<nodeup>(dir)</nodeup>
<para>Top node
</para><menu>
<menuentry>
<menunode> second node</menunode>
<menutitle> second node</menutitle>
<menucomment>
</menucomment>
</menuentry><menuentry>
<menunode> third node</menunode>
<menutitle> third node</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</node>
<node>
<nodename>second node</nodename>
<nodenext>third node</nodenext>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>

<para>second node
</para>
</node>
<node>
<nodename>third node</nodename>
<nodeprev>second node</nodeprev>
<nodeup>Top</nodeup>


</node>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->

=== Distrotech/texinfo/texinfo/texi2html/test/sectioning/res_xml/part_chapter_after_top/part_chapter_after_top.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>part_chapter_after_top.xml</setfilename>

<node>
<nodename>Top</nodename>
<nodenext>chapter</nodenext>
<nodeup>(dir)</nodeup>
</node>
<top>
<title>top</title>

<menu>
<menuentry>
<menunode>chapter</menunode>
<menutitle>chapter</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</top>
<part>
<title>part</title>

<node>
<nodename>chapter</nodename>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>chapter</title>

</chapter>
</part>
</texinfo>

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/test_refs_nodes/test_refs.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>test_refs.xml</setfilename>
<node>
<nodename>Top</nodename>
<nodenext>other nodes</nodenext>
<nodeup>(dir)</nodeup>
</node>
<top>
<title>Test refs</title>

<menu>
<menuentry>
<menunode>other nodes</menunode>
<menutitle>other nodes</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<subheading>Testing distant nodes</subheading>

<para> a  node  <xref><xrefnodename>a node</xrefnodename><xrefinfofile>manual</xrefinfofile></xref>&linebreak;
</para><example xml:space="preserve">mono : manual.html#a-node
split: ../manual/a-node.html#a-node
</example>
<para>: <xref><xrefnodename>:</xrefnodename><xrefinfofile>manual</xrefinfofile></xref>
</para><example xml:space="preserve">mono : manual.html#_003a
split: ../manual/_003a.html#_003a
</example>
<para>Top <xref><xrefnodename>top</xrefnodename><xrefinfofile>manual</xrefinfofile></xref>&linebreak; 
</para><example xml:space="preserve">mono : manual.html#Top
split: ../manual/index.html#Top
</example>
<para>(texinfo)Cross References <xref><xrefnodename>(texinfo)Cross References</xrefnodename></xref>
</para><example xml:space="preserve">mono: texinfo.html#Cross-References
split: ../texinfo/Cross-References.html#Cross-References
</example>
<subheading>Testing manual name</subheading>

<para>../manual/doc.texi <xref><xrefnodename>node</xrefnodename><xrefinfofile>../manual/doc.texi</xrefinfofile></xref>&linebreak;
</para><example xml:space="preserve">mono : doc.html#node
split: ../doc/node.html#node
</example>
<subheading>Testing local nodes</subheading>

<para>!_&quot;#$%&amp;'()*+-./;&lt;=&gt;?[\]^_`|~ <xref><xrefnodename>!_&quot;#$%&amp;'()*+-./;&lt;=&gt;?[\]^_`|~</xrefnodename></xref>&linebreak;
</para><example xml:space="preserve">target: #_0021_005f_0022_0023_0024_0025_0026_0027_0028_0029_002a_002b_002d_002e_002f_003b_003c_003d_003e_003f_005b_005c_005d_005e_005f_0060_007c_007e
</example>
<para>Top <xref><xrefnodename>Top</xrefnodename></xref>
</para><example xml:space="preserve">target: #Top
</example>
<para> local   node <xref><xrefnodename>local node</xrefnodename></xref>
</para><example xml:space="preserve">target: #local-node
</example>
</top>
<node>
<nodename>other nodes</nodename>
<nodenext>!_&quot;#$%&amp;'()*+-./;&lt;=&gt;?[\]^_`|~</nodenext>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>Chapter with nodes</title>

<example xml:space="preserve">id: other-nodes
</example>
<para>Top <xref><xrefnodename>Top</xrefnodename></xref>
</para><example xml:space="preserve">target: #Top
</example>
<menu>
<menuentry>
<menunode>!_&quot;#$%&amp;'()*+-./;&lt;=&gt;?[\]^_`|~</menunode>
<menutitle>!_&quot;#$%&amp;'()*+-./;&lt;=&gt;?[\]^_`|~</menutitle>
<menucomment>
</menucomment>
</menuentry><menuentry>
<menunode>local node</menunode>
<menutitle>local node</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</chapter>
<node>
<nodename>!_&quot;#$%&amp;'()*+-./;&lt;=&gt;?[\]^_`|~</nodename>
<nodenext>local node</nodenext>
<nodeprev>other nodes</nodeprev>
<nodeup>other nodes</nodeup>
</node>
<example xml:space="preserve">id: _0021_005f_0022_0023_0024_0025_0026_0027_0028_0029_002a_002b_002d_002e_002f_003b_003c_003d_003e_003f_005b_005c_005d_005e_005f_0060_007c_007e
</example>
<node>
<nodename>local node</nodename>
<nodeprev>!_&quot;#$%&amp;'()*+-./;&lt;=&gt;?[\]^_`|~</nodeprev>
<nodeup>other nodes</nodeup>
</node>
<example xml:space="preserve">id: local-node
</example>
</texinfo>

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/one_node_no_node/one_node.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>one_node.xml</setfilename>

<para>Garbage
</para>
<node>
<nodename>one node</nodename>
<nodeup>(dir)</nodeup>
</node>
<para>Top node
</para>
<para>anchor ref <anchor name="ref"></anchor>.
</para>
<menu>
<menuentry>
<menunode>(gcc)</menunode>
<menutitle>(gcc)</menutitle>
<menucomment> ref to gcc
</menucomment>
</menuentry></menu>


<para>ref to ref <xref><xrefnodename>ref</xrefnodename></xref>.
</para>
<para>Some text.
</para>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->
