=== Distrotech/texinfo/texinfo/makeinfo/texinfo.dtd
<!-- $Id: texinfo.dtd,v 1.7 2003-11-11 04:12:17 dirt Exp $
   Document Type Definition for Texinfo.

   Author: Philippe Martin (feloy@free.fr)
   Contributors:
           Karl Eichwalder (keichwa@gmx.net)
	   Alper Ersoy (dirt@gtk.org)

   Copyright (C) 2001, 2002, 2003 Free Software Foundation, Inc.

  Copying and distribution of this file, with or without modification,
  are permitted in any medium without royalty provided the copyright
  notice and this notice are preserved.

-->

<!-- ENTITIES -->

<!-- Meta-information -->
<!ENTITY % metainformation "setfilename | settitle | dircategory">
<!ENTITY % variables "setvalue | clearvalue">

<!-- Document language -->
<!ENTITY % lang "documentlanguage">

<!-- Language codes -->
<!ENTITY % languagecodes "aa|ab|af|am|ar|as|ay|az|ba|be|bg|bh|bi|bn|bo|br|ca|co|cs|cy|da|de|dz|el|en|eo|es|et|eu|fa|fi|fj|fo|fr|fy|ga|gd|gl|gn|gu|ha|he|hi|hr|hu|hy|ia|id|ie|ik|is|it|iu|ja|jw|ka|kk|kl|km|kn|ko|ks|ku|ky|la|ln|lo|lt|lv|mg|mi|mk|ml|mn|mo|mr|ms|mt|my|na|ne|nl|no|oc|om|or|pa|pl|ps|pt|qu|rm|rn|ro|ru|rw|sa|sd|sg|sh|si|sk|sl|sm|sn|so|sq|sr|ss|st|su|sv|sw|ta|te|tg|th|ti|tk|tl|tn|to|tr|ts|tt|tw|ug|uk|ur|uz|vi|vo|wo|xh|yi|yo|za|zh|zu">

<!-- ToC -->
<!ENTITY % toc "contents | shortcontents">

<!-- Title page -->
<!ENTITY % titlepage_cmds "author | booktitle | booksubtitle">

<!-- block -->
<!-- ***** -->
<!ENTITY % block "menu | para | quotation | example | smallexample | lisp
                  | smalllisp | cartouche | copying
                  | format | smallformat | display
                  | smalldisplay | itemize | enumerate | sp | center | group
                  | table | multitable | definition">

<!-- API definitions -->
<!-- *************** -->
<!ENTITY % definition.cmds "defcategory | deffunction | defvariable | defparam
			    | defdelimiter | deftype | defparamtype | defdatatype
			    | defclass | defclassvar | defoperation">

<!-- Headings -->
<!-- ******** -->
<!ENTITY % headings "majorheading | chapheading | heading | subheading
		     | subsubheading">


<!-- Sectioning -->
<!-- ********** -->
<!ENTITY % section.level1 "top | chapter | unnumbered | appendix">

<!ENTITY % section.level2 "section | unnumberedsec | appendixsec">

<!ENTITY % section.level3 "subsection | unnumberedsubsec | appendixsubsec">

<!ENTITY % section.level4 "subsubsection | unnumberedsubsubsec 
                           | appendixsubsubsec">

<!ENTITY % section.all "%section.level1; | %section.level2; | %section.level3;
                        | %section.level4;">


<!ENTITY % section.level1.content "(%block; 
                                   | %section.level2; 
                                   | %section.level3; 
                                   | %section.level4; 
				   | verbatim | titlepage | %toc;
				   | %lang; | %variables;
				   | %headings;
                                   | printindex)*">

<!ENTITY % section.level2.content "(%block; 
                                   | %section.level3; 
                                   | %section.level4;
				   | verbatim | titlepage | %toc;
				   | %lang; | %variables;
				   | %headings;)*">

<!ENTITY % section.level3.content "(%block; 
                                   | %section.level4;
				   | verbatim | titlepage | %toc;
				   | %lang; | %variables;
				   | %headings;)*">

<!ENTITY % section.level4.content "(%block;
				    | verbatim | titlepage | %toc;
				    | %lang; | %variables;
				    | %headings;)*">


<!-- Inline -->
<!-- ****** -->
<!ENTITY % Inline.emphasize "strong | emph">
<!ENTITY % Inline.smallcaps "sc">
<!ENTITY % Inline.fonts "i | b | tt | r | titlefont">
<!ENTITY % Inline.markup "code | command | env | file | option | samp | dfn | cite | key | kbd | var | acronym | url">
<!ENTITY % Inline.reference "xref | inforef | indexterm | email | uref">

<!ENTITY % Inline.phrase
           "%Inline.emphasize; | %Inline.smallcaps; | %Inline.fonts;
            | %Inline.markup; | %Inline.reference; ">


<!-- ************ -->
<!-- * ELEMENTS * -->
<!-- ************ -->

<!-- TOP Level Element -->
<!-- ***************** -->
<!ELEMENT texinfo ((%metainformation; | titlepage | node | %block; | %toc;
		    | %variables; | %lang;)* )>
<!ATTLIST texinfo xml:lang (%languagecodes;) 'en'>

<!-- meta-information -->
<!ELEMENT setfilename (#PCDATA)>
<!ELEMENT settitle    (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT dircategory (#PCDATA)>

<!ELEMENT setvalue    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT clearvalue  EMPTY>
<!ATTLIST setvalue
		name CDATA #REQUIRED>
<!ATTLIST clearvalue
		name CDATA #REQUIRED>

<!-- ToC -->
<!ELEMENT contents      EMPTY>
<!ELEMENT shortcontents EMPTY>

<!-- Document language -->
<!ELEMENT documentlanguage EMPTY>
<!ATTLIST documentlanguage xml:lang (%languagecodes;) 'en'>

<!-- Titlepage -->
<!ELEMENT titlepage    (%titlepage_cmds; | %block;)*>
<!ELEMENT author       (#PCDATA | %Inline.phrase;)*>
<!ELEMENT booktitle    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT booksubtitle (#PCDATA | %Inline.phrase;)*>

<!-- NODES -->
<!-- ***** -->
<!ELEMENT node (nodename, nodenext?, nodeprev?, nodeup?, 
                (%section.all; | %block; | %toc; | %lang;)*) >

<!ELEMENT nodename (#PCDATA)>
<!ELEMENT nodenext (#PCDATA)>
<!ELEMENT nodeprev (#PCDATA)>
<!ELEMENT nodeup   (#PCDATA)>

<!-- SECTIONING -->
<!-- ********** -->

<!ELEMENT top           (title?, (%section.level1.content;))>

<!ELEMENT chapter       (title?, (%section.level1.content;))>
<!ELEMENT section       (title?, (%section.level2.content;))>
<!ELEMENT subsection    (title?, (%section.level3.content;))>
<!ELEMENT subsubsection (title?, (%section.level4.content;))>

<!ELEMENT unnumbered          (title?, (%section.level1.content;))>
<!ELEMENT unnumberedsec       (title?, (%section.level2.content;))>
<!ELEMENT unnumberedsubsec    (title?, (%section.level3.content;))>
<!ELEMENT unnumberedsubsubsec (title?, (%section.level4.content;))>

<!ELEMENT appendix          (title?, (%section.level1.content;))>
<!ELEMENT appendixsec       (title?, (%section.level2.content;))>
<!ELEMENT appendixsubsec    (title?, (%section.level3.content;))>
<!ELEMENT appendixsubsubsec (title?, (%section.level4.content;))>

<!-- Headings and titles -->
<!ELEMENT majorheading  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT chapheading   (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT heading       (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT subheading    (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT subsubheading (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT title		(#PCDATA | %Inline.phrase; | footnote)*>

<!-- BLOCK Elements -->
<!-- ************** -->

<!ELEMENT quotation    (%block; | %Inline.phrase;)*>
<!ELEMENT example      (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smallexample (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT lisp         (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smalllisp    (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT cartouche    (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT copying      (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT format       (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smallformat  (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT display      (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smalldisplay (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT center       (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT group        (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT image        (#PCDATA)>

<!-- Whitespace in these elements are always preserved -->
<!ATTLIST example      xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smallexample xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST lisp         xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smalllisp    xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST display      xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smalldisplay xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST format       xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smallformat  xml:space (preserve) #FIXED 'preserve'>

<!ELEMENT verbatim     (#PCDATA)>
<!ATTLIST verbatim     xml:space (preserve) #FIXED 'preserve'>

<!ELEMENT para         (#PCDATA | %Inline.phrase; | footnote | %lang;)*>
<!ATTLIST para
	  role CDATA #IMPLIED>

<!ELEMENT menu ((menuentry | para)*)>
<!ELEMENT menuentry (menunode?, menutitle?, menucomment?)>
<!ELEMENT menunode (#PCDATA)>
<!ELEMENT menutitle (#PCDATA)>
<!ELEMENT menucomment (#PCDATA | para)*>

<!-- Lists -->
<!ELEMENT itemize (itemfunction, (item | itemize | enumerate | indexterm)*)>
<!ELEMENT enumerate (enumarg?, (item | itemize | enumerate)*)>
<!ATTLIST enumerate 
          first CDATA #IMPLIED>

<!ELEMENT item (%block;)*>
<!ELEMENT enumarg (#PCDATA)>

<!ELEMENT itemfunction (#PCDATA | %Inline.phrase;)*>

<!-- Tables -->
<!ELEMENT table (tableitem | indexterm)+>
<!ELEMENT tableitem (tableterm+, item)>
<!ELEMENT tableterm (#PCDATA | %Inline.phrase;)*>

<!ELEMENT multitable (columnfraction*, row*)>
<!ELEMENT columnfraction (#PCDATA)>
<!ELEMENT row (entry*)>
<!ELEMENT entry (#PCDATA | %Inline.phrase;)*>

<!-- API definitions -->
<!ELEMENT definition (definitionterm | definitionitem)+>
<!ELEMENT definitionterm (%definition.cmds; | indexterm)+>
<!ELEMENT definitionitem (%block;)*>

<!ELEMENT defcategory  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT deffunction  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defvariable  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defparam     (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defdelimiter (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT deftype      (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defparamtype (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defdatatype  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defclass     (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defclassvar  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defoperation (#PCDATA | %Inline.phrase; | footnote)*>

<!-- INLINE Elements -->
<!-- *************** -->

<!-- Emphasize -->
<!ELEMENT strong (#PCDATA | %Inline.phrase;)*>
<!ELEMENT emph   (#PCDATA | %Inline.phrase;)*>

<!-- small caps -->
<!ELEMENT sc (#PCDATA | %Inline.phrase;)*>

<!-- fonts -->
<!ELEMENT i  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT b  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT tt (#PCDATA | %Inline.phrase;)*>
<!ELEMENT r  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT notfixedwidth (#PCDATA | %Inline.phrase;)*>
<!ELEMENT titlefont   (#PCDATA | %Inline.phrase;)*>

<!-- markup -->
<!ELEMENT code    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT command (#PCDATA | %Inline.phrase;)*>
<!ELEMENT env     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT file    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT option  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT samp    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT dfn     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT cite    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT key     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT kbd     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT var     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT acronym (#PCDATA | %Inline.phrase;)*>
<!ELEMENT url     (#PCDATA | %Inline.phrase;)*>

<!-- reference -->
<!ELEMENT anchor EMPTY>
<!ATTLIST anchor
          name CDATA #IMPLIED>

<!ELEMENT xref (xrefnodename | xrefinfoname | xrefinfofile
                | xrefprintedname | xrefprinteddesc)*>
<!ELEMENT xrefnodename    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefinfoname    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefinfofile    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefprintedname (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefprinteddesc (#PCDATA | %Inline.phrase;)*>

<!ELEMENT inforef (inforefnodename | inforefrefname | inforefinfoname)*>
<!ELEMENT inforefnodename (#PCDATA | %Inline.phrase;)*>
<!ELEMENT inforefrefname  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT inforefinfoname (#PCDATA | %Inline.phrase;)*>

<!ELEMENT indexterm (#PCDATA | %Inline.phrase;)*>
<!ATTLIST indexterm
          index CDATA #IMPLIED>

<!ELEMENT email (emailaddress, emailname?)>
<!ELEMENT emailaddress (#PCDATA | %Inline.phrase;)*>
<!ELEMENT emailname (#PCDATA | %Inline.phrase;)*>

<!ELEMENT uref (urefurl, urefdesc?, urefreplacement?)>
<!ELEMENT urefurl         (#PCDATA | %Inline.phrase;)*>
<!ELEMENT urefdesc        (#PCDATA | %Inline.phrase;)*>
<!ELEMENT urefreplacement (#PCDATA | %Inline.phrase;)*>

<!ELEMENT footnote (para)>



<!ENTITY tex        "TeX">
<!ENTITY ellipsis   "">
<!ENTITY lt         "">
<!ENTITY gt         "">
<!ENTITY bullet     "">
<!ENTITY copyright  "">
<!ENTITY registered "">
<!ENTITY minus      "">
<!ENTITY linebreak  "">
<!ENTITY space      "">
<!ENTITY dots       "">
<!ENTITY enddots    "">
<!ENTITY amp        "">
<!ENTITY ldquo      "">
<!ENTITY rdquo      "">
<!ENTITY mdash      "">
<!ENTITY ndash      "">

<!ENTITY auml "">
<!ENTITY ouml "">
<!ENTITY uuml "">
<!ENTITY Auml "">
<!ENTITY Ouml "">
<!ENTITY Uuml "">
<!ENTITY Euml "">
<!ENTITY euml "">
<!ENTITY Iuml "">
<!ENTITY iuml "">
<!ENTITY yuml "">
<!ENTITY uml  "">

<!ENTITY Aacute "">
<!ENTITY Eacute "">
<!ENTITY Iacute "">
<!ENTITY Oacute "">
<!ENTITY Uacute "">
<!ENTITY Yacute "">
<!ENTITY aacute "">
<!ENTITY eacute "">
<!ENTITY iacute "">
<!ENTITY oacute "">
<!ENTITY uacute "">
<!ENTITY yacute "">

<!ENTITY ccedil "">
<!ENTITY Ccedil "">

<!ENTITY Acirc "">
<!ENTITY Ecirc "">
<!ENTITY Icirc "">
<!ENTITY Ocirc "">
<!ENTITY Ucirc "">
<!ENTITY acirc "">
<!ENTITY ecirc "">
<!ENTITY icirc "">
<!ENTITY ocirc "">
<!ENTITY ucirc "">

<!ENTITY Agrave "">
<!ENTITY Egrave "">
<!ENTITY Igrave "">
<!ENTITY Ograve "">
<!ENTITY Ugrave "">
<!ENTITY agrave "">
<!ENTITY egrave "">
<!ENTITY igrave "">
<!ENTITY ograve "">
<!ENTITY ugrave "">

<!ENTITY Atilde "">
<!ENTITY Ntilde "">
<!ENTITY Otilde "">
<!ENTITY atilde "">
<!ENTITY ntilde "">
<!ENTITY otilde "">

<!ENTITY oslash "">
<!ENTITY Oslash "">

<!ENTITY iexcl "">
<!ENTITY pound "">
<!ENTITY iquest "">
<!ENTITY AElig "">
<!ENTITY aelig "">
<!ENTITY OElig "">
<!ENTITY oelig "">
<!ENTITY Aring "">
<!ENTITY aring "">
<!ENTITY szlig "">

<!ENTITY macr "">


<!-- fixxme: not yet classified -->

<!ELEMENT sp (#PCDATA)>
<!ATTLIST sp
          lines CDATA #IMPLIED>
<!ELEMENT printindex (#PCDATA)>

=== Distrotech/texinfo/texinfo/texi2html/test/sectioning/res_xml/text_before_line_command/text_before_node_command.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<para>before setfilename <setfilename>text_before_node_command.xml</setfilename>
</para>
<para>before title <booktitle>the title</booktitle>
</para>
<node>
<nodename>Top</nodename>
<nodenext>LD Version Scripts</nodenext>
<nodeup>(dir)</nodeup>
</node>
<chapter>
<title>test text before a node</title>

<menu>
<menuentry>
<menunode>LD Version Scripts</menunode>
<menutitle>LD Version Scripts</menutitle>
<menucomment>
</menucomment>
</menuentry><menuentry>
<menunode>ttt</menunode>
<menutitle>ttt</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<para>i@node LD Version Scripts
&mdash; </para>@chapter LD Version Scripts

<para>ddd <contents></contents>
</para>
<quotation>
<para>aaa <author>quotation author</author>
quotation
</para></quotation>

</chapter>
<node>
<nodename>ttt</nodename>
<nodeprev>Top</nodeprev>
</node>
<chapter>
<title>ttt chap</title>

<shortcontents></shortcontents>

</chapter>
</texinfo>

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/rec_nodes/rec_nodes.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>rec_nodes.xml</setfilename>


<node>
<nodename>Top</nodename>
<nodenext>second node</nodenext>
<nodeup>(dir)</nodeup>
</node>
<para>Top node
</para>
<menu>
<menuentry>
<menunode>second node</menunode>
<menutitle>second node</menutitle>
<menucomment>
</menucomment>
</menuentry><menuentry>
<menunode>node following second</menunode>
<menutitle>node following second</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<node>
<nodename>second node</nodename>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<para>second node (@node second node,,top,TOP).
<!-- anchor TOP: @anchor{TOP}. -->
</para>
<menu>
<menuentry>
<menunode>other node</menunode>
<menutitle>other node</menutitle>
<menucomment>
</menucomment>
</menuentry><menuentry>
<menunode>second node</menunode>
<menutitle>second node</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<node>
<nodename>other node</nodename>
<nodeup>second node</nodeup>
</node>
<!-- anchor top @anchor{top}. -->
<!-- ref to TOP @ref{TOP}. -->

<menu>
<menuentry>
<menunode>other node</menunode>
<menutitle>other node</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<node>
<nodename>node up node following second</nodename>
<nodeup>node following second</nodeup>
</node>
<menu>
<menuentry>
<menunode>node following second</menunode>
<menutitle>node following second</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<para>in node up node following second
</para>
<node>
<nodename>node following second</nodename>
<nodeup>node up node following second</nodeup>
</node>

<para>in node following second
</para><menu>
<menuentry>
<menunode>node up node following second</menunode>
<menutitle>node up node following second</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/semi_auto/semi_auto.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>semi_auto.xml</setfilename>

<node>
<nodename>Top</nodename>
<nodenext>Chap1</nodenext>
<nodeup>(dir)</nodeup>
</node>
<unnumbered>
<title>Top</title>

<menu>
<menuentry>
<menunode>Chap1</menunode>
<menutitle>Chap1</menutitle>
<menucomment>
</menucomment>
</menuentry><menuentry>
<menunode>Section non auto</menunode>
<menutitle>Section non auto</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</unnumbered>
<node>
<nodename>Chap1</nodename>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>Chapter 1</title>

<menu>
<menuentry>
<menunode>Sec in chapter</menunode>
<menutitle>Sec in chapter</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<node>
<nodename>Sec in chapter</nodename>
<nodenext>Section non auto</nodenext>
<nodeup>Chap1</nodeup>
</node>
<section>
<title>Sec in chapter</title>

</section>
<node>
<nodename>Section non auto</nodename>
<nodeprev>Chap1</nodeprev>
<nodeup>Top</nodeup>
</node>
<section>
<title>Section</title>

</section>
</chapter>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/before_node_and_section/before_node_and_section.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>before_node_and_section.xml</setfilename>

<para>Garbage
ref to Top <xref><xrefnodename>Top</xrefnodename></xref>.
<indexterm index="cp">index entry before anything</indexterm>Hey<footnote><para>a footnote
</para></footnote>.
An anchor <anchor name="anchor1"></anchor>.
</para>
<menu>
<menuentry>
<menunode>node1</menunode>
<menutitle>node1</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<node>
<nodename>Top</nodename>
<nodenext>node1</nodenext>
<nodeup>(dir)</nodeup>
</node>
<unnumbered>
<title>top @top section</title>
<para>Node top
</para>
<para>ref to anchor1<footnote><para>another footnote
</para></footnote>, which is before @node Top: <xref><xrefnodename>anchor1</xrefnodename></xref>.
</para><menu>
<menuentry>
<menunode>node1</menunode>
<menutitle>node1</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</unnumbered>
<node>
<nodename>node1</nodename>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>node1 chapter</title>

<printindex>cp</printindex>

</chapter>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/one_section/one_section.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>one_section.xml</setfilename>

<para>Garbage
</para>
<subsection>
<title>The subsection</title>

<para>anchor ref <anchor name="ref"></anchor>.
</para>
<menu>
<menuentry>
<menunode>(gcc)</menunode>
<menutitle>(gcc)</menutitle>
<menucomment> ref to gcc
</menucomment>
</menuentry></menu>


<para>ref to ref <xref><xrefnodename>ref</xrefnodename></xref>.
</para>
<para>Some text.
</para>
</subsection>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/section_chapter_before_top/section_chapter_before_top.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>section_chapter_before_top.xml</setfilename>

<section>
<title>section</title>

</section>
<chapter>
<title>chapter</title>

</chapter>
<top>
<title>top</title>

</top>
</texinfo>

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/part_node_before_top/part_node_before_top.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>part_node_before_top.xml</setfilename>

<node>
<nodename>part node before top</nodename>
<nodenext>Top</nodenext>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<part>
<title>part</title>

</part>
<node>
<nodename>Top</nodename>
<nodenext>part node before top</nodenext>
<nodeprev>part node before top</nodeprev>
<nodeup>(dir)</nodeup>
</node>
<top>
<title>top</title>

<menu>
<menuentry>
<menunode>part node before top</menunode>
<menutitle>part node before top</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</top>
</texinfo>

=== Distrotech/texinfo/texinfo/texi2html/test/sectioning/res_xml/part_node_appendix/part_node_appendix.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>part_node_appendix.xml</setfilename>

<node>
<nodename>Top</nodename>
<nodenext>chapter node</nodenext>
<nodeup>(dir)</nodeup>
</node>
<top>
<title>top</title>

<menu>
<menuentry>
<menunode>chapter node</menunode>
<menutitle>chapter node</menutitle>
<menucomment>
</menucomment>
</menuentry><menuentry>
<menunode>appendix node</menunode>
<menutitle>appendix node</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</top>
<part>
<title>Part 1</title>

<node>
<nodename>chapter node</nodename>
<nodenext>appendix node</nodenext>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>chapter</title>

</chapter>
</part>
<node>
<nodename>appendix node</nodename>
<nodeprev>chapter node</nodeprev>
<nodeup>Top</nodeup>
</node>
<appendix>
<title>Appendix</title>

</appendix>
</texinfo>
