=== Distrotech/texinfo/texinfo/makeinfo/texinfo.dtd
<!-- $Id: texinfo.dtd,v 1.7 2003-11-11 04:12:17 dirt Exp $
   Document Type Definition for Texinfo.

   Author: Philippe Martin (feloy@free.fr)
   Contributors:
           Karl Eichwalder (keichwa@gmx.net)
	   Alper Ersoy (dirt@gtk.org)

   Copyright (C) 2001, 2002, 2003 Free Software Foundation, Inc.

  Copying and distribution of this file, with or without modification,
  are permitted in any medium without royalty provided the copyright
  notice and this notice are preserved.

-->

<!-- ENTITIES -->

<!-- Meta-information -->
<!ENTITY % metainformation "setfilename | settitle | dircategory">
<!ENTITY % variables "setvalue | clearvalue">

<!-- Document language -->
<!ENTITY % lang "documentlanguage">

<!-- Language codes -->
<!ENTITY % languagecodes "aa|ab|af|am|ar|as|ay|az|ba|be|bg|bh|bi|bn|bo|br|ca|co|cs|cy|da|de|dz|el|en|eo|es|et|eu|fa|fi|fj|fo|fr|fy|ga|gd|gl|gn|gu|ha|he|hi|hr|hu|hy|ia|id|ie|ik|is|it|iu|ja|jw|ka|kk|kl|km|kn|ko|ks|ku|ky|la|ln|lo|lt|lv|mg|mi|mk|ml|mn|mo|mr|ms|mt|my|na|ne|nl|no|oc|om|or|pa|pl|ps|pt|qu|rm|rn|ro|ru|rw|sa|sd|sg|sh|si|sk|sl|sm|sn|so|sq|sr|ss|st|su|sv|sw|ta|te|tg|th|ti|tk|tl|tn|to|tr|ts|tt|tw|ug|uk|ur|uz|vi|vo|wo|xh|yi|yo|za|zh|zu">

<!-- ToC -->
<!ENTITY % toc "contents | shortcontents">

<!-- Title page -->
<!ENTITY % titlepage_cmds "author | booktitle | booksubtitle">

<!-- block -->
<!-- ***** -->
<!ENTITY % block "menu | para | quotation | example | smallexample | lisp
                  | smalllisp | cartouche | copying
                  | format | smallformat | display
                  | smalldisplay | itemize | enumerate | sp | center | group
                  | table | multitable | definition">

<!-- API definitions -->
<!-- *************** -->
<!ENTITY % definition.cmds "defcategory | deffunction | defvariable | defparam
			    | defdelimiter | deftype | defparamtype | defdatatype
			    | defclass | defclassvar | defoperation">

<!-- Headings -->
<!-- ******** -->
<!ENTITY % headings "majorheading | chapheading | heading | subheading
		     | subsubheading">


<!-- Sectioning -->
<!-- ********** -->
<!ENTITY % section.level1 "top | chapter | unnumbered | appendix">

<!ENTITY % section.level2 "section | unnumberedsec | appendixsec">

<!ENTITY % section.level3 "subsection | unnumberedsubsec | appendixsubsec">

<!ENTITY % section.level4 "subsubsection | unnumberedsubsubsec 
                           | appendixsubsubsec">

<!ENTITY % section.all "%section.level1; | %section.level2; | %section.level3;
                        | %section.level4;">


<!ENTITY % section.level1.content "(%block; 
                                   | %section.level2; 
                                   | %section.level3; 
                                   | %section.level4; 
				   | verbatim | titlepage | %toc;
				   | %lang; | %variables;
				   | %headings;
                                   | printindex)*">

<!ENTITY % section.level2.content "(%block; 
                                   | %section.level3; 
                                   | %section.level4;
				   | verbatim | titlepage | %toc;
				   | %lang; | %variables;
				   | %headings;)*">

<!ENTITY % section.level3.content "(%block; 
                                   | %section.level4;
				   | verbatim | titlepage | %toc;
				   | %lang; | %variables;
				   | %headings;)*">

<!ENTITY % section.level4.content "(%block;
				    | verbatim | titlepage | %toc;
				    | %lang; | %variables;
				    | %headings;)*">


<!-- Inline -->
<!-- ****** -->
<!ENTITY % Inline.emphasize "strong | emph">
<!ENTITY % Inline.smallcaps "sc">
<!ENTITY % Inline.fonts "i | b | tt | r | titlefont">
<!ENTITY % Inline.markup "code | command | env | file | option | samp | dfn | cite | key | kbd | var | acronym | url">
<!ENTITY % Inline.reference "xref | inforef | indexterm | email | uref">

<!ENTITY % Inline.phrase
           "%Inline.emphasize; | %Inline.smallcaps; | %Inline.fonts;
            | %Inline.markup; | %Inline.reference; ">


<!-- ************ -->
<!-- * ELEMENTS * -->
<!-- ************ -->

<!-- TOP Level Element -->
<!-- ***************** -->
<!ELEMENT texinfo ((%metainformation; | titlepage | node | %block; | %toc;
		    | %variables; | %lang;)* )>
<!ATTLIST texinfo xml:lang (%languagecodes;) 'en'>

<!-- meta-information -->
<!ELEMENT setfilename (#PCDATA)>
<!ELEMENT settitle    (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT dircategory (#PCDATA)>

<!ELEMENT setvalue    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT clearvalue  EMPTY>
<!ATTLIST setvalue
		name CDATA #REQUIRED>
<!ATTLIST clearvalue
		name CDATA #REQUIRED>

<!-- ToC -->
<!ELEMENT contents      EMPTY>
<!ELEMENT shortcontents EMPTY>

<!-- Document language -->
<!ELEMENT documentlanguage EMPTY>
<!ATTLIST documentlanguage xml:lang (%languagecodes;) 'en'>

<!-- Titlepage -->
<!ELEMENT titlepage    (%titlepage_cmds; | %block;)*>
<!ELEMENT author       (#PCDATA | %Inline.phrase;)*>
<!ELEMENT booktitle    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT booksubtitle (#PCDATA | %Inline.phrase;)*>

<!-- NODES -->
<!-- ***** -->
<!ELEMENT node (nodename, nodenext?, nodeprev?, nodeup?, 
                (%section.all; | %block; | %toc; | %lang;)*) >

<!ELEMENT nodename (#PCDATA)>
<!ELEMENT nodenext (#PCDATA)>
<!ELEMENT nodeprev (#PCDATA)>
<!ELEMENT nodeup   (#PCDATA)>

<!-- SECTIONING -->
<!-- ********** -->

<!ELEMENT top           (title?, (%section.level1.content;))>

<!ELEMENT chapter       (title?, (%section.level1.content;))>
<!ELEMENT section       (title?, (%section.level2.content;))>
<!ELEMENT subsection    (title?, (%section.level3.content;))>
<!ELEMENT subsubsection (title?, (%section.level4.content;))>

<!ELEMENT unnumbered          (title?, (%section.level1.content;))>
<!ELEMENT unnumberedsec       (title?, (%section.level2.content;))>
<!ELEMENT unnumberedsubsec    (title?, (%section.level3.content;))>
<!ELEMENT unnumberedsubsubsec (title?, (%section.level4.content;))>

<!ELEMENT appendix          (title?, (%section.level1.content;))>
<!ELEMENT appendixsec       (title?, (%section.level2.content;))>
<!ELEMENT appendixsubsec    (title?, (%section.level3.content;))>
<!ELEMENT appendixsubsubsec (title?, (%section.level4.content;))>

<!-- Headings and titles -->
<!ELEMENT majorheading  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT chapheading   (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT heading       (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT subheading    (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT subsubheading (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT title		(#PCDATA | %Inline.phrase; | footnote)*>

<!-- BLOCK Elements -->
<!-- ************** -->

<!ELEMENT quotation    (%block; | %Inline.phrase;)*>
<!ELEMENT example      (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smallexample (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT lisp         (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smalllisp    (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT cartouche    (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT copying      (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT format       (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smallformat  (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT display      (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT smalldisplay (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT center       (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT group        (#PCDATA | %block; | %Inline.phrase;)*>
<!ELEMENT image        (#PCDATA)>

<!-- Whitespace in these elements are always preserved -->
<!ATTLIST example      xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smallexample xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST lisp         xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smalllisp    xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST display      xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smalldisplay xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST format       xml:space (preserve) #FIXED 'preserve'>
<!ATTLIST smallformat  xml:space (preserve) #FIXED 'preserve'>

<!ELEMENT verbatim     (#PCDATA)>
<!ATTLIST verbatim     xml:space (preserve) #FIXED 'preserve'>

<!ELEMENT para         (#PCDATA | %Inline.phrase; | footnote | %lang;)*>
<!ATTLIST para
	  role CDATA #IMPLIED>

<!ELEMENT menu ((menuentry | para)*)>
<!ELEMENT menuentry (menunode?, menutitle?, menucomment?)>
<!ELEMENT menunode (#PCDATA)>
<!ELEMENT menutitle (#PCDATA)>
<!ELEMENT menucomment (#PCDATA | para)*>

<!-- Lists -->
<!ELEMENT itemize (itemfunction, (item | itemize | enumerate | indexterm)*)>
<!ELEMENT enumerate (enumarg?, (item | itemize | enumerate)*)>
<!ATTLIST enumerate 
          first CDATA #IMPLIED>

<!ELEMENT item (%block;)*>
<!ELEMENT enumarg (#PCDATA)>

<!ELEMENT itemfunction (#PCDATA | %Inline.phrase;)*>

<!-- Tables -->
<!ELEMENT table (tableitem | indexterm)+>
<!ELEMENT tableitem (tableterm+, item)>
<!ELEMENT tableterm (#PCDATA | %Inline.phrase;)*>

<!ELEMENT multitable (columnfraction*, row*)>
<!ELEMENT columnfraction (#PCDATA)>
<!ELEMENT row (entry*)>
<!ELEMENT entry (#PCDATA | %Inline.phrase;)*>

<!-- API definitions -->
<!ELEMENT definition (definitionterm | definitionitem)+>
<!ELEMENT definitionterm (%definition.cmds; | indexterm)+>
<!ELEMENT definitionitem (%block;)*>

<!ELEMENT defcategory  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT deffunction  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defvariable  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defparam     (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defdelimiter (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT deftype      (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defparamtype (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defdatatype  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defclass     (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defclassvar  (#PCDATA | %Inline.phrase; | footnote)*>
<!ELEMENT defoperation (#PCDATA | %Inline.phrase; | footnote)*>

<!-- INLINE Elements -->
<!-- *************** -->

<!-- Emphasize -->
<!ELEMENT strong (#PCDATA | %Inline.phrase;)*>
<!ELEMENT emph   (#PCDATA | %Inline.phrase;)*>

<!-- small caps -->
<!ELEMENT sc (#PCDATA | %Inline.phrase;)*>

<!-- fonts -->
<!ELEMENT i  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT b  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT tt (#PCDATA | %Inline.phrase;)*>
<!ELEMENT r  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT notfixedwidth (#PCDATA | %Inline.phrase;)*>
<!ELEMENT titlefont   (#PCDATA | %Inline.phrase;)*>

<!-- markup -->
<!ELEMENT code    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT command (#PCDATA | %Inline.phrase;)*>
<!ELEMENT env     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT file    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT option  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT samp    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT dfn     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT cite    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT key     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT kbd     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT var     (#PCDATA | %Inline.phrase;)*>
<!ELEMENT acronym (#PCDATA | %Inline.phrase;)*>
<!ELEMENT url     (#PCDATA | %Inline.phrase;)*>

<!-- reference -->
<!ELEMENT anchor EMPTY>
<!ATTLIST anchor
          name CDATA #IMPLIED>

<!ELEMENT xref (xrefnodename | xrefinfoname | xrefinfofile
                | xrefprintedname | xrefprinteddesc)*>
<!ELEMENT xrefnodename    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefinfoname    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefinfofile    (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefprintedname (#PCDATA | %Inline.phrase;)*>
<!ELEMENT xrefprinteddesc (#PCDATA | %Inline.phrase;)*>

<!ELEMENT inforef (inforefnodename | inforefrefname | inforefinfoname)*>
<!ELEMENT inforefnodename (#PCDATA | %Inline.phrase;)*>
<!ELEMENT inforefrefname  (#PCDATA | %Inline.phrase;)*>
<!ELEMENT inforefinfoname (#PCDATA | %Inline.phrase;)*>

<!ELEMENT indexterm (#PCDATA | %Inline.phrase;)*>
<!ATTLIST indexterm
          index CDATA #IMPLIED>

<!ELEMENT email (emailaddress, emailname?)>
<!ELEMENT emailaddress (#PCDATA | %Inline.phrase;)*>
<!ELEMENT emailname (#PCDATA | %Inline.phrase;)*>

<!ELEMENT uref (urefurl, urefdesc?, urefreplacement?)>
<!ELEMENT urefurl         (#PCDATA | %Inline.phrase;)*>
<!ELEMENT urefdesc        (#PCDATA | %Inline.phrase;)*>
<!ELEMENT urefreplacement (#PCDATA | %Inline.phrase;)*>

<!ELEMENT footnote (para)>



<!ENTITY tex        "TeX">
<!ENTITY ellipsis   "">
<!ENTITY lt         "">
<!ENTITY gt         "">
<!ENTITY bullet     "">
<!ENTITY copyright  "">
<!ENTITY registered "">
<!ENTITY minus      "">
<!ENTITY linebreak  "">
<!ENTITY space      "">
<!ENTITY dots       "">
<!ENTITY enddots    "">
<!ENTITY amp        "">
<!ENTITY ldquo      "">
<!ENTITY rdquo      "">
<!ENTITY mdash      "">
<!ENTITY ndash      "">

<!ENTITY auml "">
<!ENTITY ouml "">
<!ENTITY uuml "">
<!ENTITY Auml "">
<!ENTITY Ouml "">
<!ENTITY Uuml "">
<!ENTITY Euml "">
<!ENTITY euml "">
<!ENTITY Iuml "">
<!ENTITY iuml "">
<!ENTITY yuml "">
<!ENTITY uml  "">

<!ENTITY Aacute "">
<!ENTITY Eacute "">
<!ENTITY Iacute "">
<!ENTITY Oacute "">
<!ENTITY Uacute "">
<!ENTITY Yacute "">
<!ENTITY aacute "">
<!ENTITY eacute "">
<!ENTITY iacute "">
<!ENTITY oacute "">
<!ENTITY uacute "">
<!ENTITY yacute "">

<!ENTITY ccedil "">
<!ENTITY Ccedil "">

<!ENTITY Acirc "">
<!ENTITY Ecirc "">
<!ENTITY Icirc "">
<!ENTITY Ocirc "">
<!ENTITY Ucirc "">
<!ENTITY acirc "">
<!ENTITY ecirc "">
<!ENTITY icirc "">
<!ENTITY ocirc "">
<!ENTITY ucirc "">

<!ENTITY Agrave "">
<!ENTITY Egrave "">
<!ENTITY Igrave "">
<!ENTITY Ograve "">
<!ENTITY Ugrave "">
<!ENTITY agrave "">
<!ENTITY egrave "">
<!ENTITY igrave "">
<!ENTITY ograve "">
<!ENTITY ugrave "">

<!ENTITY Atilde "">
<!ENTITY Ntilde "">
<!ENTITY Otilde "">
<!ENTITY atilde "">
<!ENTITY ntilde "">
<!ENTITY otilde "">

<!ENTITY oslash "">
<!ENTITY Oslash "">

<!ENTITY iexcl "">
<!ENTITY pound "">
<!ENTITY iquest "">
<!ENTITY AElig "">
<!ENTITY aelig "">
<!ENTITY OElig "">
<!ENTITY oelig "">
<!ENTITY Aring "">
<!ENTITY aring "">
<!ENTITY szlig "">

<!ENTITY macr "">


<!-- fixxme: not yet classified -->

<!ELEMENT sp (#PCDATA)>
<!ATTLIST sp
          lines CDATA #IMPLIED>
<!ELEMENT printindex (#PCDATA)>

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/node_part_chapter_after_top/node_part_chapter_after_top.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>node_part_chapter_after_top.xml</setfilename>

<node>
<nodename>Top</nodename>
<nodenext>chapter node</nodenext>
<nodeup>(dir)</nodeup>
</node>
<top>
<title>top</title>

<menu>
<menuentry>
<menunode>chapter node</menunode>
<menutitle>chapter node</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</top>
<node>
<nodename>chapter node</nodename>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<part>
<title>part</title>

<chapter>
<title>chapter</title>

</chapter>
</part>
</texinfo>

=== Distrotech/texinfo/texinfo/texi2html/test/sectioning/res_xml/section_chapter_before_top_nodes/section_chapter_before_top_nodes.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>section_chapter_before_top_nodes.xml</setfilename>

<node>
<nodename>section node</nodename>
</node>
<section>
<title>section</title>

</section>
<node>
<nodename>chapter node</nodename>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>chapter</title>

<menu>
<menuentry>
<menunode>section node</menunode>
<menutitle>section node</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</chapter>
<node>
<nodename>Top</nodename>
<nodenext>chapter node</nodenext>
<nodeprev>chapter node</nodeprev>
<nodeup>(dir)</nodeup>
</node>
<top>
<title>top</title>

<menu>
<menuentry>
<menunode>chapter node</menunode>
<menutitle>chapter node</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>


</top>
</texinfo>

=== Distrotech/texinfo/texinfo/texi2html/test/formatting/res_info/direntry_dircategory_xml/direntry_dircategory.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>direntry_dircategory.xml</setfilename>

<dircategory>&ldquo;category&mdash;<var>th  ere</var>?&rdquo;</dircategory>
<direntry>
<menuentry>
<menunode>(foo)</menunode>
<menutitle> foo</menutitle>
<menucomment>   &ldquo;hello&mdash;<var>there</var>?&rdquo;
</menucomment>
</menuentry></direntry>

<dircategory>cat2</dircategory>
<direntry>
<menuentry>
<menunode>aaa</menunode>
<menutitle>aaa </menutitle>
<menucomment>               aaaa
                   bbbbb
</menucomment>
</menuentry>
<para>menutitle
</para></direntry>


<node>
<nodename>Top</nodename>
<nodenext>chapter</nodenext>
<nodeup>(dir)</nodeup>
</node>
<top>
<title>Test dircategory and direntry</title>

<para>Text
<dircategory>in text</dircategory>
</para><direntry>
<menuentry>
<menunode>(in_text)</menunode>
<menutitle> in text</menutitle>
<menucomment> in text
</menucomment>
</menuentry></direntry>

<menu>
<menuentry>
<menunode>chapter</menunode>
<menutitle>chapter</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</top>
<node>
<nodename>chapter</nodename>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>chapter</title>

<para>In chapter
</para>
</chapter>
</texinfo>

=== Distrotech/texinfo/texinfo/texi2html/test/sectioning/res_xml/node-whitespace_plain/node-whitespace.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>node-whitespace.xml</setfilename>

<!-- Makeinfo should collapse whitespace in node names. -->


<node>
<nodename>Top</nodename>
<nodenext>Chap 1.3</nodenext>
<nodeup>(dir)</nodeup>
</node>
<top>
<title>Whitespace in Node Names</title>


<menu>
<menuentry>
<menunode>Chap 1.3</menunode>
<menutitle>Chap  1.3  </menutitle>
<menucomment>
</menucomment>
</menuentry><menuentry>
<menunode>Chap 1.4</menunode>
<menutitle> Chap  1.4  </menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</top>
<node>
<nodename>Chap 1.3</nodename>
<nodenext>Chap 1.4</nodenext>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>Chap 1.3</title>

<para>Can I reach here?
</para>
</chapter>
<node>
<nodename>Chap 1.4</nodename>
<nodeprev>Chap 1.3</nodeprev>
<nodeup>Top</nodeup>
</node>
<chapter>
<title>Another space test</title>

<para>How about here?
See <xref><xrefnodename>Chap 1.3</xrefnodename></xref>.
</para>
</chapter>
</texinfo>

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/top_without_node/top_without_node.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>top_without_node.xml</setfilename>

<para>Garbage
</para>
<node>
<nodename>a node</nodename>
<nodeup>(dir)</nodeup>
</node>
<unnumbered>
<title>unnumbered</title>

<para>in unnumbered
</para>
</unnumbered>
<unnumbered>
<title>top section</title>
<para>Top section
</para>
<titlefont>The top section, no top node</titlefont>

<node>
<nodename>second</nodename>
<nodeup>(dir)</nodeup>
</node>
<section>
<title>second</title>

<para>second node
</para>
</section>
</unnumbered>
<chapter>
<title>Chapter</title>

<para>Text of chapter
</para>
</chapter>
<chapter>
<title>Chapter 2</title>


<para>Text of chapter 2
</para>
</chapter>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/section_before_top/section_before_top.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>section_before_top.xml</setfilename>

<node>
<nodename>section node</nodename>
<nodeprev>Top</nodeprev>
<nodeup>Top</nodeup>
</node>
<section>
<title>section</title>

</section>
<node>
<nodename>Top</nodename>
<nodenext>section node</nodenext>
<nodeprev>section node</nodeprev>
<nodeup>(dir)</nodeup>
</node>
<top>
<title>top</title>

<menu>
<menuentry>
<menunode>section node</menunode>
<menutitle>section node</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</top>
</texinfo>

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/nodes_before_top/nodes_before_top.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>nodes_before_top.xml</setfilename>

<node>
<nodename>first</nodename>
<nodenext>Top</nodenext>
<nodeup>(dir)</nodeup>

<para>in first node
</para><menu>
<menuentry>
<menunode> node in menu before top</menunode>
<menutitle> node in menu before top</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

<titlefont>A titlefont in a node</titlefont>

</node>
<node>
<nodename>node in menu before top</nodename>
<nodeup>first</nodeup>

<para>node in menu before top text
</para>
</node>
<node>
<nodename>Top</nodename>
<nodeprev>first</nodeprev>
<unnumbered>
<title>top section</title>
<para>Top node
</para><menu>
<menuentry>
<menunode> second node</menunode>
<menutitle> second node</menutitle>
<menucomment>
</menucomment>
</menuentry></menu>

</unnumbered>
</node>
<node>
<nodename>second node</nodename>
<nodeup>Top</nodeup>
<chapter>
<title>a chapter</title>

<para>second node
</para>


</chapter>
</node>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->

=== Distrotech/texinfo/texinfo/texi2html/test/sectionning/res_xml/test_two_include/test_two_include.xml
<?xml version="1.0"?>
<!DOCTYPE texinfo PUBLIC "-//GNU//DTD TexinfoML V4.12//EN" "http://www.gnu.org/software/texinfo/dtd/4.12/texinfo.dtd">
<texinfo xml:lang="en">

<setfilename>test_two_include.xml</setfilename>

<node>
<nodename>Top</nodename>
<nodeup>(dir)</nodeup>
</node>

<para>Include version
<setvalue name="UPDATED">28 March 2002</setvalue>
<setvalue name="UPDATED-MONTH">March 2002</setvalue>
<setvalue name="EDITION">4.2</setvalue>
<setvalue name="VERSION">4.2</setvalue>
</para>
<para>include inc_file
In included file.
</para>
<para>After inclusion.
</para>
</texinfo>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-indent-step:1
sgml-indent-data:nil
End:
-->
